### ISSUE TITLE
Entity Yapısının Kurulması 

### ISSUE THREAD

**Issue by mustafaergan** [mustafaergan/Java-19-Web-Proje-Omer#1]
Entity'ler
Personel(id,name)
Sunucu(id,isim, sorumlu personel,Ram miktarı, cpu miktarı, işletim sistemi, rdp adresi, açıklama)
Kullanıcı(id,name,rol_id,personel_id)
Rol(id,rol)

**Comment by OmerYILMAZ61** [comment]
hocam tam olarak nasıl olucak :)

**Comment by mustafaergan** [comment]
şu şekilde personel-kullanici arasında 1-1 ilişki olacak. Kullanici-rol arasında 1-m ilişki olacak. sunucu-personel 1-m ilişki olacak.

**Comment by OmerYILMAZ61** [comment]
entitiyleri kurdum hocam
